[build]
  publish = "build"
  command = "npm run build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"


[[redirects]]
from = "/api/*"            # Route API requests to functions
to = "/.netlify/functions/:splat"
status = 200